version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  backend:
    build: ./backendnodejs
    ports:
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/todoapp
    networks:
      - backend-network

  frontend:
    build: ./frontendreactjs
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - frontend-network

volumes:
  mongo-data:

networks:
  backend-network:
  frontend-network:
