version: '3.8'

services:
  mongo:
    image: mongo:latest  # Use official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Use a volume to persist data

  backend:
    build: ./backendnodejs  # Build the backend from the ./backendnodejs directory
    ports:
      - "3100:3100"  # Expose the backend on port 3100
    depends_on:
      - mongo  # Ensure that MongoDB is up before starting the backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp  # Pass the MongoDB URI to the backend

  frontend:
    build: ./frontendreactjs  # Build the frontend from the ./frontendreactjs directory
    ports:
      - "3000:80"  # Expose port 80 inside the container to port 3000 on the host
    depends_on:
      - backend  # Ensure the backend is up before starting the frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for React hot-reloading

volumes:
  mongo-data:  # MongoDB data volume
