version: '3.8'

services:
  mongo:
    image: mongo:latest  # Official MongoDB image
    ports:
      - "27017:27017"  # Expose MongoDB port
    volumes:
      - mongo-data:/data/db  # Data persistence
    networks:
      - backend-network  # Assign MongoDB to the backend network

  backend:
    build: ./backendnodejs  # Build backend from the given directory
    ports:
      - "3100:3100"  # Expose port 3100 for backend
    depends_on:
      - mongo  # Ensure MongoDB is ready before starting backend
    environment:
        MONGO_URI=mongodb://mongo:27017/todoapp  # Set MongoDB URI for backend service
    networks:
      - backend-network  # Ensure backend is on the same network as MongoDB

  frontend:
    build: ./frontendreactjs  # Build frontend from the given directory
    ports:
      - "3000:80"  # Expose port 3000 for frontend (Nginx listens on port 80 inside container)
    depends_on:
      - backend  # Ensure backend is ready before starting frontend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessary for proper file watching in development
    networks:
      - frontend-network  # Keep frontend on a separate network

volumes:
  mongo-data:  # MongoDB data volume for persistence

networks:
  backend-network:
  frontend-network:
