version: '3.8'

services:
  mongo:
    image: mongo:latest  # ✅ Official MongoDB image
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backendnodejs
    ports:
      - "3100:3100"  # ✅ Backend listening on port 3100
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp  # ✅ MongoDB URI passed as environment variable

  frontend:
    build: ./frontendreactjs
    ports:
      - "3000:80"  # ✅ Frontend uses Nginx, so mapping port 80 inside container to 3000
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:  # ✅ Mongo data volume
