version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backendnodejs
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/todoapp
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontendreactjs
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    # Removed wait-for-it.sh to avoid crash

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
