version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backendnodejs
    ports:
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/todoapp
    networks:
      - app-network

  frontend:
    build:
      context: ./frontendreactjs
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://backend:3100
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
