version: '3.8'

services:
  mongo:
    image: mongo:latest  # ✅ Official MongoDB image
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backendnodejs
    ports:
      - "3100:3100"  
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp  # ✅ Pass MongoDB URI

  frontend:
    build: ./frontendreactjs
    ports:
      - "3000:80"  # ✅ Port 80 inside container because of Nginx
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
