version: '3.8'
services:
  mongo:
    build: ./DBmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backendnodejs
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontendreactjs
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
