apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack
spec:
  selector:
    role: backend
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 30008
  type: NodePort
